server:
  port: 8090
  servlet:
    context-path: /credit-simulator/v1

logging:
  level:
    root: info
  pattern:
    console: "[%boldBlue(%thread)] [%highlight(%-5level)] %cyan(%d{yyyy-MM-dd HH:mm:ss}) | %magenta(%logger{36}) : %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"

spring:
  application:
    name: credit-simulator
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/credit_simulator
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
  sql:
    init:
      platform: postgresql
