services:
  postgres:
    container_name: db
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credit_simulator

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
        - "25672:25672"
        - "15672:15672"
    volumes:
        - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
    restart: always

networks:
  api:
    driver: bridge